The aggregator test can break discovery while removing an apiservice
Other tests that depend on discovery not failing can be affected by the removal
of an apiservice mid test:

```
error: Unable to to get list of available resources: unable to retrieve the complete
list of server APIs: wardle.k8s.io/v1alpha1: the server could not find the requested
resource
```