fix(stepfunctions-tasks): call-rest-api `CallApiGatewayRestApiEndpoint` does not support `JsonATA` for api_path (#37738)
### Issue # (if applicable)

Closes #37728 .

### Reason for this change

- `CallApiGatewayRestApiEndpoint` fails during synthesis when apiPath is provided as a JSONata expression.

Error message during cdk synthesis :
```
(.venv) ➜  cdkAppPython git:(main) ✗ cdk synth 
jsii.errors.JavaScriptError: 
  ValidationError: "path" must begin with a "/": '{% "/path/" & $states.input.path_suffix %}'
```

- This cdk synthesis failure prevents us from passing `JsonATA` expression in `api_path` & there is NO workaround .

IAM policy must be resolved at synth time .
JSONata expressions are evaluated at runtime by Step Functions .

- This PR focuses on resolving the issue detailed below : 
https://github.com/aws/aws-cdk/issues/37728 .



### Description of changes
1.  Detect when `apiPath` is a JSONata expression ({% ... %}).
I've used the same `isValidJsonataExpression` logic to maintain consistency .
https://github.com/aws/aws-cdk/blob/e207b76cc2503701b3c4e2c87023617b485b2fde/packages/aws-cdk-lib/aws-stepfunctions/lib/private/jsonata.ts#L1

2. When JSONata detected, use wildcard path `/*` as the IAM policy path ARN while keeping the original expression unchanged in the Step Functions definition .

This `apiPath` behavior matches existing handling in CallApiGatewayHttpApiEndpoint


### Describe any new or updated permissions being added
- No new permissions introduced .
- Existing `execute-api:Invoke` permission now uses a wildcard path (/*) when apiPath is dynamic .
- Scope still remains limited to 
```
arn:partition:execute-api:<region>:<account>:<api-id>/<stage>/<method>/*
```




### Description of how you validated changes

1. Unit tests added:
- JSONata `apiPath` does not throw during synthesis
- JSONata expression is passed through unchanged in state JSON

2. Integration test added (aws-stepfunctions-tasks):
- IAM policy with wildcard path (/*) = ```.....<api-id>/<stage>/<method>/*```
- State machine definition preserving JSONata expression

3. I've also manually verified the correctness of IAM policy, Jsonata expression evaluation on the deployed resources.
( included in integ tests CFN )



### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*