kubeadm: fix build failure
Used kubeadm Printer object in the
FetchInitConfigurationFromCluster call to fix this build issue:

   app/cmd/alpha/certs.go:271:68: cannot use out (type io.Writer)
        as type output.Printer in argument to config.FetchInitConfigurationFromCluster:
            io.Writer does not implement output.Printer (missing Close method)