test: fix import path to client-go/util/retry
Change d6ffcae31d79c8b86fe14b97149e070bf6967443 introduced a broken import path
containing the staging/ directory.

In particular, this leads to bazel build failures such as:

$ bazel build -- //... -//vendor/...
...
ERROR: .../src/k8s.io/kubernetes/test/integration/daemonset/BUILD:8:1: GoCompile test/integration/daemonset/linux_amd64_stripped/go_default_test~/test/integration/daemonset/go_default_test.a failed (Exit 1): compile failed: error executing command
...
Use --sandbox_debug to see verbose messages from the sandbox
GoCompile: missing strict dependencies:
	.../4cab8d21a8b5319c1f602c5c3c69fd07/sandbox/linux-sandbox/2661/execroot/__main__/test/integration/daemonset/daemonset_test.go: import of "k8s.io/kubernetes/staging/src/k8s.io/client-go/util/retry"
Known dependencies are:
...
  k8s.io/client-go/util/retry
...
FAILED: Build did NOT complete successfully