Kubelet: fix uid detection by reverting "Use consistent imageRef during container startup"
This reverts commit 5769863fa0046ad7ba8f5f80ee331c3eee543f40.

The reverted commit breaks uid detection and images which are using a
different uid than 0 will run as root (0).

E.g. in my case many things just were broken because I like to use pod
security policies and all the non-root-images did not start after the
update to v1.14.2 with the error message

    Error: container has runAsNonRoot and image will run as root

Workaround is to use a Security Context which defines the uid to use so
that pods don't depend on the USER defined in the images.