apis/apps/fuzzer: add missing MaxUnavailable defaulting
Include defaulting in the StatefulSet fuzzer for the field
RollingUpdate.MaxUnavailable, otherwise when the feature gate
MaxUnavailableStatefulSet is enabled it changes the default
in SetDefaults_StatefulSet from /pkg/apis/apps/v1/defaults.go.

That can cause errors such as:
  --- FAIL: TestRoundTripTypes (1.05s)

...

  - MaxUnavailable: nil,
  + MaxUnavailable: s"1",