Allow setting a context when the config does not have one
To enable this sub command, it was necessary to propagate the error
further up the calling chain for inspection. All the subcommands of
config, can now look at the error and decide whether the can continue or
not. As the only command that should still work is "use-context" they
all stop with error if a context is not set.
But this was not enough, since the config is also read while doing the
actual write, it was needed to check for the actually command which was
running. Hence, the signature of `ModifyConfig` and `writeCurrentContext`
was updated. If the use-context subcommand is called the last argument
is set to `true`, this signals that it's OK to ignore the error
`NoConextSet` and continue the execution.
This set of changes displays the error:
```
error: Multiple contexts found. However, no current-context is set in the configuration
```
If running, for example, `kubectl get pods`, but it still allows one to
`get-contexts` and `use-context` quickly from the command line to fix the probelm.

Demo:
```
$ ./kubectl get pods
error: Multiple contexts found. However, no current-context is set in the configuration
$ ./kubectl config get-contexts
CURRENT   NAME               CLUSTER            AUTHINFO         NAMESPACE
          coldsweet          microk8s-cluster   admin-microk8s   coldsweet
          devops             devops-calico      admin
          devops-cilium      devops-cilium      admin-cilium
          microk8s-context   microk8s-cluster   admin-microk8s
$ ./kubectl config use-context devops
Switched to context "devops".
./kubectl get pods
NAME                          READY   STATUS    RESTARTS   AGE
nginx-blue-9cf945578-6gsmz    1/1     Running   0          20d
nginx-green-df5fcc8d5-xk7ww   1/1     Running   0          20d
```