Make kubectl explain usable with resources from aggregated API servers
Before this commit, kubectl explain would look up the API version in
scheme.Registry, but that's not really necessary, because the API
version is already in the gvk variable.

Resources from aggregated API servers, such as those from the Service
Catalog API server, aren't in the registry, which causes this:

$ kubectl explain clusterservicebroker
error: group servicecatalog.k8s.io has not been registered