Raise error if the user has multiple contexts but no current set
The current behavior is to ignore this and try to connect to
localhost:8080. [This is quite confusing, as reported in this issue][1].

This commit improves the UX by telling the users they need to explicitly
choose a context in the that multiple context exist:

```
$ kubectl get pods
error: Multiple contexts found. However, no current-context is set in the configuration
```

[1]: https://github.com/kubernetes/kubectl/issues/936