golangci-lint: switch to new module plugin mode, support changing directory
It is now possible to invoke golangci-lint inside a sub-directory:

    kubernetes/staging/src/k8s.io/dynamic-resource-allocation$ ../../../../hack/verify-golangci-lint.sh -n ./...
    installing golangci-lint and logcheck plugin from hack/tools into /nvme/gopath/src/k8s.io/kubernetes/_output/local/bin
    INFO Cloning golangci-lint repository
    INFO Adding plugin imports
    INFO generated imports info /tmp/custom-gcl2511569860/golangci-lint/cmd/golangci-lint/plugins.go:
    package main

    import (
    	_ "sigs.k8s.io/logtools/logcheck/gclplugin"
    )

    INFO Adding replace directives
    INFO run: go get sigs.k8s.io/logtools@v0.8.1
    INFO Running go mod tidy
    INFO Building golangci-lint binary
    INFO Moving golangci-lint binary
    running /nvme/gopath/src/k8s.io/kubernetes/_output/local/bin/golangci-lint run --color=always --config=/nvme/gopath/src/k8s.io/kubernetes/hack/golangci.yaml ./...
    ...
    ERROR: kubeletplugin/draplugin.go:521:51: non-wrapping format verb for fmt.Errorf. Use `%w` to format errors (errorlint)
    ERROR: 		return nil, fmt.Errorf("start node client: %v", err)
    ERROR: 		                                                ^
    ...

Support for changing the directory depends on avoiding the relative lookup path
for the logcheck plugin. This can be done by building logcheck as a module into
a custom golangci-lint binary. This also allows removing some other workarounds
for the path.

The downside is that building golangci-lint now needs to be done twice (once to
bootstrap, once to include the plugin) and needs to check out the golangci-lint
GitHub repo (done under the hood by `golangci-lint custom`).