Revert "Speed up pkg/kubelet/podcertificate tests with synctest"
This reverts commit d17b4548245288515101be6719c0a807cfafe6d2.

The synctest bubble occasionally fails with:

    --- FAIL: TestFullFlow (0.01s)
    panic: deadlock: main bubble goroutine has exited but blocked goroutines remain [recovered, repanicked]

The code running inside the bubble seems to leak a goroutine. That must be
fixed before the commit can be re-applied.