webhook admission: avoid risk of flakes
The unit test flaked at least once so far in the CI. Cannot be reproduced
locally, though.

    === RUN   TestGetMutatingWebhookConfigSmartReload/create_configuration_and_update_moar_of_them
        mutating_webhook_manager_test.go:238: Expected number of webhooks 4 received 0
        mutating_webhook_manager_test.go:245: Expected number of creations 4 received 0
        mutating_webhook_manager_test.go:266: Expected final number of webhooks 5 received 3
    --- FAIL: TestGetMutatingWebhookConfigSmartReload/create_configuration_and_update_moar_of_them (2.00s)

There were two potential root causes:
- The watch must be set up completely before creating objects (a fake
  client-go limitation).
- The delay might be too small on a loaded system.

By running the tests in a synctest bubble with synctest.Wait calls at
the right places both problems are avoided. As a welcome side effect
the test also completes faster.

Before:

    ok  	k8s.io/apiserver/pkg/admission/configuration	21.036s

After:

    ok  	k8s.io/apiserver/pkg/admission/configuration	4.023s

    2m0s: 13502 runs so far, 0 failures, 512 active